### ISSUE TITLE
Deployments to GCP not working

### ISSUE THREAD

**Issue by alexabbott** [daveteu/nextjs-google-cloud-functions#1]
Upon running `npm run deploy` the following error is presented:

```
message=Build failed: function.js does not exist; Error ID: 7485c5b6
```

After changing `server.js` to `function.js` the following error is presented:

```
 message=Function failed on loading user code. This is likely due to a bug in the user code.
```

**Comment by marceloogeda** [comment]
I faced the same issue.

I've configured the following Github Actions to deploy to gcf. 

```yml
name: Deploy on GCF (Production)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Read .nvmrc file
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install dependencies
        run: |
          npm i

      - name: Build
        run: |
          npm ci --legacy-peer-deps
          npm run build

      - name: Setup Google Cloud
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID_PROD }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SERVICE_KEY_PROD }}

      - name: Delpoy to GCP
        uses: actions-hub/gcloud@master
        with:
          args: |
            functions deploy \
            --project ${{ secrets.GOOGLE_PROJECT_ID_PROD }} \
            functionName \
            --entry-point handler \
            --trigger-http \
            --runtime nodejs12 \
            --memory=128MB \
            --allow-unauthenticated
```

I also needed to create my own `.gcloudignore` file. 

I hope it helps.
